=== craibuc/crystal-xmlresume/resume.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio 2012 Developer Edition (Trial) 10.1.9.4348 (http://www.liquid-technologies.com)-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="resume">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="metadata" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="lastModified" type="xs:dateTime" use="optional" />
                        <xs:attribute name="author" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="100" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="objective" minOccurs="0">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="1000" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="person" type="PersonType" minOccurs="0" />
                <xs:element name="academics" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="degrees" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="degree" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="level" type="xs:string" minOccurs="0" />
                                                    <xs:element name="major" type="xs:string" minOccurs="0" />
                                                    <xs:element name="minor" type="xs:string" minOccurs="0" />
                                                    <xs:element name="institution" type="xs:string" minOccurs="0" />
                                                    <xs:element name="annotation" minOccurs="0" />
                                                </xs:sequence>
                                                <xs:attribute name="graduated" type="xs:date" use="optional" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="certifications" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="certification" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="projects" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="project">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="client" type="ClientType" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="summary" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="1000" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="accomplishments" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="accomplishment">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:maxLength value="500" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="technologies" type="xs:string" minOccurs="0" maxOccurs="1" />
                                    </xs:sequence>
                                    <xs:attribute name="startingDate" type="xs:date" use="required" />
                                    <xs:attribute name="endingDate" type="xs:date" use="optional" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="AddressType">
        <xs:sequence>
            <xs:element name="room" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="10" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="street" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="100" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="city" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="100" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="regionCode" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="2" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="postalCode" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="10" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="countryCode" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="2" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ClientType">
        <xs:sequence>
            <xs:element name="location" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="url" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:anyURI">
                    <xs:maxLength value="255" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="PersonType">
        <xs:sequence>
            <xs:element name="address" type="AddressType" minOccurs="0" />
            <xs:element name="contact" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="phone" minOccurs="0">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="50" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="email" minOccurs="0">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="50" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="url" minOccurs="0">
                            <xs:simpleType>
                                <xs:restriction base="xs:anyURI">
                                    <xs:maxLength value="255" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="linkedIn" type="xs:anyURI" minOccurs="0" maxOccurs="1" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="givenName" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:maxLength value="50" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="surName" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:maxLength value="50" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== craibuc/crystal-xmlresume/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<resume xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resume.xsd">
	<metadata lastModified="2014-04-18T13:17:00" author="Craig Buchanan"/>
	<objective>Nam tempus mollis imperdiet. Curabitur eu justo ultrices, tempus lectus a, venenatis felis. Sed auctor aliquam ligula id ullamcorper. Duis ante purus, porttitor ac tortor eu, sagittis semper ipsum. Donec nibh nunc, dictum eget lectus vel, interdum malesuada lorem. Nulla iaculis mi eget adipiscing lacinia. Nullam euismod lectus id elementum posuere. Quisque placerat ut est eu luctus. Aliquam sit amet semper dolor. </objective>
	<person givenName="First" surName="Last">
		<address>
			<room>#100</room>
			<street>XXXX Hennepin Avenue South</street>
			<city>Minneapolis</city>
			<regionCode>MN</regionCode>
			<postalCode>55555</postalCode>
			<countryCode>US</countryCode>
		</address>
		<contact>
			<phone>+1.612.999.9999</phone>
			<email>first.last@domain.com</email>
			<url>http://www.domain.com</url>
            <linkedIn>http://linkedin.com/in/lastfirst</linkedIn>
		</contact>
	</person>
	<academics>
		<degrees>
			<degree graduated="2000-06-01">
				<level>MBA</level>
				<major>Management Information Systems</major>
				<minor/>
				<institution>Foobar University</institution>
				<annotation/>
			</degree>
			<degree graduated="1900-06-01">
				<level>BBA</level>
				<major>Finance</major>
				<minor>Economics</minor>
				<institution>University of Foobar</institution>
				<annotation/>
			</degree>
		</degrees>
	</academics>
    <certifications>
        <certification>Certification ABC</certification>
        <certification>Certification XYZ</certification>
        <certification>Certification 123</certification>
        <certification>Certification 456</certification>
	</certifications>
	
	<projects>
		
        <project startingDate="2014-01-01">
            <client name="Foo Foo Foo Foo Foo Foo" url="http://www.foo.org"><location>New York, NY</location></client>
            <summary>Nullam luctus porta enim, non fermentum ligula laoreet sed. Fusce molestie egestas interdum.</summary>
            <accomplishments>
                <accomplishment>Nam tempus mollis imperdiet. Curabitur eu justo ultrices, tempus lectus a, venenatis felis. Sed auctor aliquam ligula id ullamcorper. Duis ante purus, porttitor ac tortor eu, sagittis semper ipsum. Donec nibh nunc, dictum eget lectus vel, interdum malesuada lorem. </accomplishment>
                <accomplishment>Nam tempus mollis imperdiet. Curabitur eu justo ultrices, tempus lectus a, venenatis felis. Sed auctor aliquam ligula id ullamcorper. Duis ante purus, porttitor ac tortor eu, sagittis semper ipsum. Donec nibh nunc, dictum eget lectus vel, interdum malesuada lorem. </accomplishment>
            </accomplishments>
            <technologies>BusinessObjects XI, Crystal Reports, Oracle 10g, Universe, WebIntelligence, BusinessView</technologies>
        </project>
		
        <project startingDate="2013-01-01" endingDate="2013-12-31">
            <client name="Bar Bar Bar Bar Bar Bar" url="http://www.bar.org"><location>Baltimore, MD</location></client>
            <summary>Nullam luctus porta enim, non fermentum ligula laoreet sed. Fusce molestie egestas interdum.</summary>
            <accomplishments>
                <accomplishment>Nam tempus mollis imperdiet. Curabitur eu justo ultrices, tempus lectus a, venenatis felis. Sed auctor aliquam ligula id ullamcorper. Duis ante purus, porttitor ac tortor eu, sagittis semper ipsum. Donec nibh nunc, dictum eget lectus vel, interdum malesuada lorem. </accomplishment>
                <accomplishment>Nam tempus mollis imperdiet. Curabitur eu justo ultrices, tempus lectus a, venenatis felis. Sed auctor aliquam ligula id ullamcorper. Duis ante purus, porttitor ac tortor eu, sagittis semper ipsum. Donec nibh nunc, dictum eget lectus vel, interdum malesuada lorem. </accomplishment>
            </accomplishments>
            <technologies>BusinessObjects XI, Crystal Reports 2008, Oracle 10g, Universe, WebIntelligence, BusinessView</technologies>
        </project>
		
		<project startingDate="2012-02-01" endingDate="2012-12-31">
            <client name="Foobar Foobar Foobar Foobar" url="http://www.foobar.org/"><location>St. Paul, MN</location></client>
            <summary>Nullam luctus porta enim, non fermentum ligula laoreet sed. Fusce molestie egestas interdum.</summary>
            <accomplishments>
                <accomplishment>Nam tempus mollis imperdiet. Curabitur eu justo ultrices, tempus lectus a, venenatis felis. Sed auctor aliquam ligula id ullamcorper. Duis ante purus, porttitor ac tortor eu, sagittis semper ipsum. Donec nibh nunc, dictum eget lectus vel, interdum malesuada lorem. </accomplishment>
                <accomplishment>Nam tempus mollis imperdiet. Curabitur eu justo ultrices, tempus lectus a, venenatis felis. Sed auctor aliquam ligula id ullamcorper. Duis ante purus, porttitor ac tortor eu, sagittis semper ipsum. Donec nibh nunc, dictum eget lectus vel, interdum malesuada lorem. </accomplishment>
            </accomplishments>
            <technologies>BusinessObjects XI, Crystal Reports XI, Oracle 10g, Universe, WebIntelligence</technologies>
		</project>

	</projects>
	
</resume>
